global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'status-go'
    static_configs:
      - targets: ['host.docker.internal:9305']  # Status-go exposes metrics on port 9305 by default
    metrics_path: '/metrics' 