{
 "title": "Status-Go Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Network Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "statusgo_waku_connected_peers", "legendFormat": "Connected Peers" }
   ]
  },
  {
   "title": "Peers by Shard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "statusgo_waku_peers_by_shard", "legendFormat": "{{shard}}" }
   ]
  },
  {
   "title": "Peers By Discovery Origin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "statusgo_waku_peers_by_origin", "legendFormat": "{{origin}}" },
    {
     "expr": "sum(statusgo_waku_peers_by_origin)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Dial Failures By Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statusgo_waku_peer_dial_failures_total",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Rate of Dial Failures by Type",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(statusgo_waku_peer_dial_failures_total[10m])",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  { "title": "Message Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Message Stored Check",
   "type": "timeseries",
   "description": "Outgoing messages will be marked as failed if it's not get stored in 10 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "increase(statusgo_waku_store_query_successes_total[5m])",
     "legendFormat": "Store Success (5m)"
    },
    {
     "expr": "increase(statusgo_waku_store_query_failures_total[5m])",
     "legendFormat": "Store Failed (5m)"
    }
   ]
  },
  {
   "title": "Acknowledged Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "increase(statusgo_waku_message_delivery_confirmations_total[5m])",
     "legendFormat": "Acked Messages (5m)"
    }
   ]
  },
  {
   "title": "Missing Messages From Store",
   "type": "timeseries",
   "description": "Aggregate the missing messages by pubsub topic since the service started.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(statusgo_waku_missed_messages_total) by (pubsub_topic)",
     "legendFormat": "Total Missed Messages (5m) - {{pubsub_topic}}"
    }
   ]
  },
  {
   "title": "Message Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "statusgo_waku_envelope_sent_errors_total",
     "legendFormat": "Message Errors"
    }
   ]
  },
  { "title": "Bandwidth Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Total Sent Message By Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (message_type) (statusgo_waku_raw_message_sent_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sent Message by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statusgo_waku_raw_message_sent_total",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Total Bytes of Sent Message By Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by (message_type) (statusgo_waku_raw_message_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Bytes of Sent Message by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum by (message_type) (rate(statusgo_waku_raw_message_size_bytes[10m])) ",
     "legendFormat": "{{message_type}}"
    },
    {
     "expr": "sum(rate(statusgo_waku_raw_message_size_bytes[10m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Message Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "statusgo_waku_messages_sent_total",
     "legendFormat": "Messages Sent"
    },
    {
     "expr": "sum(statusgo_waku_messages_received_total)",
     "legendFormat": "Messages Received"
    }
   ]
  },
  {
   "title": "Message Size Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(statusgo_waku_message_size_bytes[5m])",
     "legendFormat": "Message Size Rate"
    }
   ]
  },
  {
   "title": "Average messages sent every 10 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "avg_over_time(statusgo_waku_messages_sent_total_count[10m])",
     "legendFormat": "{{publish_method}}"
    }
   ]
  }
 ]
}